# Project: Project1
# Makefile created by Dev-C++ 5.2.0.0

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o C:/Users/USER/Downloads/Compressed/huffman_string1/huffman.o C:/Users/USER/Downloads/Compressed/huffman_string1/pQueue.o $(RES)
LINKOBJ  = main.o C:/Users/USER/Downloads/Compressed/huffman_string1/huffman.o C:/Users/USER/Downloads/Compressed/huffman_string1/pQueue.o $(RES)
LIBS     = -L"C:/Program Files/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc  
INCS     = -I"C:/Program Files/Dev-Cpp/MinGW32/include" 
CXXINCS  = -I"C:/Program Files/Dev-Cpp/MinGW32/include" 
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS   = $(INCS)  
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Project1.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Project1.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

C:/Users/USER/Downloads/Compressed/huffman_string1/huffman.o: C:/Users/USER/Downloads/Compressed/huffman_string1/huffman.cpp
	$(CPP) -c C:/Users/USER/Downloads/Compressed/huffman_string1/huffman.cpp -o C:/Users/USER/Downloads/Compressed/huffman_string1/huffman.o $(CXXFLAGS)

C:/Users/USER/Downloads/Compressed/huffman_string1/pQueue.o: C:/Users/USER/Downloads/Compressed/huffman_string1/pQueue.cpp
	$(CPP) -c C:/Users/USER/Downloads/Compressed/huffman_string1/pQueue.cpp -o C:/Users/USER/Downloads/Compressed/huffman_string1/pQueue.o $(CXXFLAGS)
